[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_AZURE_OPENAI_API_VERSION,VITE_AZURE_OPENAI_DEPLOYMENT,VITE_ADMIN_EMAIL,VITE_READ_SAS,VITE_WRITE_SAS,VITE_AZURE_OPENAI_KEY,VITE_AZURE_OPENAI_ENDPOINT,VITE_AZURE_TABLE_URL,VITE_CLERK_PUBLISHABLE_KEY"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
